name: Auto Deploy to Mac Mini

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Notify Mac Mini to deploy
      run: |
        curl -X POST "${{ secrets.DEPLOY_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: sha256=$(echo -n '${{ toJson(github) }}' | openssl dgst -sha256 -hmac '${{ secrets.DEPLOY_WEBHOOK_SECRET }}' | cut -d' ' -f2)" \
          -H "X-GitHub-Event: push" \
          -d '{
            "ref": "${{ github.ref }}",
            "repository": {
              "full_name": "${{ github.repository }}",
              "clone_url": "${{ github.repositoryUrl }}"
            },
            "pusher": {
              "name": "${{ github.actor }}"
            },
            "head_commit": {
              "id": "${{ github.sha }}",
              "message": "${{ github.event.head_commit.message }}",
              "url": "${{ github.event.head_commit.url }}"
            }
          }'